<a href="https://colab.research.google.com/github/mdaugherity/Numerical-2021/blob/main/PHYS_451_Class_1_13_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INTRO TO PYTHON AND GOOGLE COLAB
PHYS 451, Spring 2021, Dr. Daugherity

Words show up as normal

# New Section

## Subsection

### Subsubsection

Bold words are in **two asterisks**

Italic words are in *one asterisk*

Code looks like 

```
# This is formatted as code
```

Links are [Google](https://www.google.com)


In [ ]:
# comments look like this - example python stuff

# duck typing - no need to declare variables
x = 42
x = 1.2323
x = 'asdf'

In [ ]:
# output
x  # the lazy way

'asdf'

In [ ]:
x = 42
y = 6.02e23
print(x)
print(x,y)   # work, but is UGLY


print(3**2)  # 3^2
print(2**0.5) # sqrt of 2

# Easy but ugly way to print: use print(a,b,c,d,...)
print('The sqrt of 2 is',2**0.5) # sqrt of 2

42
42 6.02e+23
9
1.4142135623730951
The sqrt of 2 is 1.4142135623730951


In [ ]:
# How to control the output
p = 3.1416
print(f"The value of pi is {p}")
print(f"The value of pi is {p:5.3f}")  # width of 5, 3 decimals, float
print(f"The value of pi is {p:1.0f}")  # no decimals
print(f"The value of pi is {p:5.2e}")     # scientific
print(f"The value of pi is {123864129387641239:,}")  # commas, wow!
x=1
y=2
z=123
print(f"{x}\t{y}\t{z}")  # make nice columns

The value of pi is 3.1416
The value of pi is 3.142
The value of pi is 3
The value of pi is 3.14e+00
The value of pi is 123,864,129,387,641,239
1	2	123


# Python Cheat Sheet

## Logic

In [ ]:
x=1
if x>0:
  print('positive')
elif x<0:
  print('negative')
else:
  print('zero')

positive


In [ ]:
if x==0:
  print('zero')

## LOOPS

In [ ]:
# while loop
i=0
while i<5:
  i+=1
  print(i)

1
2
3
4
5


In [ ]:
# for loop - ONLY WORKS ON LISTS OF THINGS!!!!!!
for i in [0,1,7,'red']:
  print(i)

0
1
7
red


In [ ]:
for i in range(4):  # WARNING: starts at 0, does not include 4
  print(i)

0
1
2
3


# ARRAYS

In [ ]:
import numpy as np

In [ ]:
# HOW TO CREATE ARRAYS
# you MUST declare before using!!!!
x = np.array([1,3,2,-5])
print(x)
y = np.array( [(1,2,3),(4,5,6) ] )
print(y)

x = np.zeros(5) 
print(x)
x = np.zeros((3,2)) 
print(x)

# SUUUUPER USEFUL FOR MAKING PLOTS
x = np.linspace(0,5,num=10)
print(x)

# SUUUUPER USEFUL FOR LOOPS
x =np.arange(4)
print(x)

[ 1  3  2 -5]
[[10 20 30]
 [40 50 60]]
[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[0 1 2 3]


## INDEXING

In [ ]:
x = np.arange(1,6)
print(x)

[1 2 3 4 5]


In [ ]:
x[3]

4

In [ ]:
for i in range(5):
  print( x[i])

1
2
3
4
5


In [ ]:
y = np.array([(1,2,3),(4,5,6)])
print(y)

[[1 2 3]
 [4 5 6]]


In [ ]:
y[1]

array([4, 5, 6])

In [ ]:
y[1][0]

4

In [ ]:
# fun tricks

In [ ]:
x[-1]  # last element

5

In [ ]:
print(x)
x[1:3]


[1 2 3 4 5]


array([2, 3])

In [ ]:
x[:3]   # first 3 elements

array([1, 2, 3])

In [ ]:
x[3:]   # element 3 to the end

array([4, 5])

In [ ]:
x[-3:]

array([3, 4, 5])

In [ ]:
# operations in numpy work on the ENTIRE array at once!
print(x)
print( np.cos(x) )
print( np.exp(x) )


[1 2 3 4 5]


array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])