<a href="https://colab.research.google.com/github/mdaugherity/Numerical-2021/blob/main/PHYS_451_Class_1_22_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PHYS 451 - Chapter 2
# Class 1-22-21
Example of solving system of linear equations


In [1]:
import numpy as np

In [2]:
A = np.array([[-0.5,1],[2,1]])
print(A)

b = np.array([1,6])
print(b)

np.linalg.solve(A,b)

[[-0.5  1. ]
 [ 2.   1. ]]
[1 6]


array([2., 2.])

In [3]:
Ainv = np.linalg.inv(A)
print('The inverse of A:')
print(Ainv,'\n')

print('Checking the inverse:')
print(np.dot(Ainv,A))

print('\nSolution:',np.dot(Ainv,b))

The inverse of A:
[[-0.4  0.4]
 [ 0.8  0.2]] 

Checking the inverse:
[[1. 0.]
 [0. 1.]]

Solution: [2. 2.]
