<a href="https://colab.research.google.com/github/mdaugherity/Numerical-2021/blob/main/PHYS_451_Class_1_20_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2.6 + 0.6

3.2

In [ ]:
2.6 + 0.2 + 0.2 + 0.2

3.2000000000000006

### COMPUTERS STORE APPROXIMATE NUMBERS, NOT EQUATIONS!!!!!

In [ ]:
bin(26)

'0b11010'

In [ ]:
13/32

0.40625

In [ ]:
1/4 +1/8 + 1/32

0.40625

In [ ]:
0.40626

0.40626

In [ ]:
1 + 1e-10

1.0000000001

In [ ]:
1 + 1e-15

1.000000000000001

In [ ]:
1+ 1e-16

1.0

In [ ]:
print( float.hex(1.0))
print( float.hex(1.0 + 1e-10))
print( float.hex(1.0 + 1e-15))
print( float.hex(1.0 + 1e-16))

0x1.0000000000000p+0
0x1.000000006df38p+0
0x1.0000000000005p+0
0x1.0000000000000p+0


In [ ]:
print( float.hex(2.6+0.6) )
print( float.hex(2.6+0.2+0.2+0.2) )

0x1.999999999999ap+1
0x1.999999999999bp+1


In [ ]:
(2**0.5)**2

2.0000000000000004

In [ ]:
(2**0.5)  * (2**0.5) - 2

4.440892098500626e-16

In [ ]:
print( float.hex((2**0.5)  * (2**0.5)) )
print( float.hex(2.0) )

0x1.0000000000001p+1
0x1.0000000000000p+1


In [ ]:
0x4B7

1207

In [ ]:
1/4 + 1/16

0.3125

In [ ]:
float.hex(0.3125)

'0x1.4000000000000p-2'

In [ ]:
float.hex(1.75)

'0x1.c000000000000p+0'

In [ ]:
2**-52

2.220446049250313e-16

In [ ]:
import numpy as np
np.finfo(float).eps

2.220446049250313e-16

In [ ]:
np.finfo(float)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

# BONUS FEATURES

In [ ]:
# Sum up vs sum down
N = 1000
sumup = 0
for i in range(1,N):   # make sure to skip zero!
  sumup+=1/i

sumdown = 0
for i in range(N-1,0,-1):  # counts down from N-1 to 1 
  sumdown +=1/i

print(sumup)
print(sumdown)
print(sumup-sumdown)

7.484470860550343
7.484470860550341
1.7763568394002505e-15


# DELETE STUFF BELOW HERE

In [ ]:
c = np.array([(1),(2)])
c.transpose().shape

(2,)

In [ ]:
print(c, c.T)

[1 2] [1 2]


In [ ]:
np.array([1,2,3]).T

array([1, 2, 3])

In [ ]:
arr = np.array([[1, 2, 3]]).T

print(arr)

[[1]
 [2]
 [3]]


In [ ]:
c.reshape(1,2)

array([[1, 2]])

In [ ]:
r = np.array([[1,2]])
c = np.array([[3],[4] ])
print(r, r.shape)
print()
print(c, c.shape)

[[1 2]] (1, 2)

[[3]
 [4]] (2, 1)


In [ ]:
# lazier way of column vectors:
c1 = np.array([[3,4]]).T    # STILL NEED TWO SETS OF [] FOR 2 DIMENSIOS
c2 = np.array([3,4]).reshape(2,1)  # Make a 1D, reshape it into 2D
print(c1)
print(c2)

[[3]
 [4]]
[[3]
 [4]]


In [ ]:
# In general using * gives element-wise multiplication (with "broadcasting...") 
print(r*r)
print(r*c)
print(c*r)
print(c*c)

[[1 4]]
[[3 6]
 [4 8]]
[[3 6]
 [4 8]]
[[ 9]
 [16]]


In [ ]:
# Use np.dot or np.matmul for actual matrix multiplication
print(np.dot(r,c))
print(np.dot(c,r))
# r.r and c.c give errors

[[11]]
[[3 6]
 [4 8]]


In [ ]:
c*r

array([[3, 6],
       [4, 8]])

In [ ]:
c*c

array([[ 9],
       [16]])

In [ ]:
np.dot(r,r)

ValueError: ignored